java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" lookup localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" rebind_attributes localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" search_count_limit localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" search_time_limit localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" search_with_filter_ret_all localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" destroy localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" bind_attributes localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" search_subtree localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" list localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" search localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" bind localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" rebind localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" unbind localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" rename localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" get_all_attributes localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" create localhost:3890
java -jar "build/libs/JNDIscover-r$(git rev-list --count HEAD).$(git rev-parse --short HEAD).jar" mod_attributes localhost:3890
