# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.hostname = "ldap.wk"

  config.vm.network :forwarded_port, guest: 389, host: 3890

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.20"

  config.vm.provision "shell", path: "install_ldap.sh"
  config.vm.provision "shell", path: "setup_ldap.sh"
end
